/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/theseus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Studio.geometry} material={nodes.Studio.material} position={[0.06, 0.04, -4.44]} scale={[-9.97, -11.14, -10.78]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials.Material} position={[0.68, 1.34, -2.57]} scale={[0.05, 0.21, 0.05]} />
      <mesh geometry={nodes.Geo_Node.geometry} material={nodes.Geo_Node.material} />
    </group>
  )
}

useGLTF.preload('/theseus.glb')
